with CTE_CHAVE_COO as (
	SELECT
	    substr(SKU.MVVC_DT_HR_ABE_SIS, 9, 2) || ':' || 
	    substr(SKU.MVVC_DT_HR_ABE_SIS, 11, 2) || ':' || 
	    substr(SKU.MVVC_DT_HR_ABE_SIS, 13, 2) AS HORA_AB,
		    substr(SKU.MVVC_DT_HR_FEC_SIS, 9, 2) || ':' || 
	    substr(SKU.MVVC_DT_HR_FEC_SIS, 11, 2) || ':' || 
	    substr(SKU.MVVC_DT_HR_FEC_SIS, 13, 2) AS HORA_FC,
		    date_diff('second',
	        parse_datetime(substr(SKU.MVVC_DT_HR_ABE_SIS, 9, 2) || ':' || 
	                       substr(SKU.MVVC_DT_HR_ABE_SIS, 11, 2) || ':' || 
	                       substr(SKU.MVVC_DT_HR_ABE_SIS, 13, 2), 'HH:mm:ss'),
	        parse_datetime(substr(SKU.MVVC_DT_HR_FEC_SIS, 9, 2) || ':' || 
	                       substr(SKU.MVVC_DT_HR_FEC_SIS, 11, 2) || ':' || 
	                       substr(SKU.MVVC_DT_HR_FEC_SIS, 13, 2), 'HH:mm:ss')
				    ) AS DIFERENCA_SEGUNDOS,
	    concat(CAST(SKU.MVVC_CD_FILIAL_MOV AS varchar), '|', 
		       CAST(SKU.MVVC_NR_ECF_MOV AS varchar), '|', 
		       CAST(SKU.NUMERO_COO AS varchar))
	 											AS CHV_FLIAL_PRD,
		count(distinct concat(CAST(SKU.MVVC_CD_FILIAL_MOV AS varchar), '|', 
                      CAST(SKU.NUMERO_COO AS varchar), '|', 
                      CAST(PRD.MVVP_NR_PRD AS varchar))) AS QTD,
		  sum(CAST(PRD.MVVP_QT_PRD * PRD.MVVP_VL_PRD_VEN AS DECIMAL(10, 2))) AS TT
    FROM modelled.cosmos_mov_v14b_dbo_mv_vda_cab SKU
    INNER JOIN modelled.cosmos_mov_v14b_dbo_mv_vda_prd PRD
        ON SKU.MVVC_NR_ECF_MOV = PRD.MVVP_NR_ECF_MOV
	        AND SKU.MVVC_CD_FILIAL_MOV = PRD.MVVP_CD_FILIAL_MOV 
	        AND SKU.MVVC_DT_MOV = PRD.MVVP_DT_MOV 
	        AND SKU.MVVC_CT_VDA = PRD.MVVP_CT_VDA 
    WHERE SKU.MVVC_ST_CAN_CPM = 'O'
        AND SKU.MVVC_DT_MOV >= date_add('day', -50, current_date)
    GROUP BY SKU.MVVC_DT_HR_ABE_SIS,SKU.MVVC_DT_HR_FEC_SIS, 
    	concat(CAST(SKU.MVVC_CD_FILIAL_MOV AS varchar), '|', CAST(SKU.MVVC_NR_ECF_MOV AS varchar), '|', CAST(SKU.NUMERO_COO AS varchar))
),
CTE_CHAVE_PRD as (
	SELECT 
	    CONCAT(CAST(CAB.MVVC_CD_FILIAL_MOV AS varchar), '|', CAST(CAB.MVVC_NR_ECF_MOV AS varchar), '|', CAST(CAB.NUMERO_COO AS varchar)) AS CHV_PPL
	FROM 
	    modelled.cosmos_mov_v14b_dbo_mv_vda_cab CAB
	INNER JOIN 
	    modelled.cosmos_mov_v14b_dbo_mv_vda_prd PRD
	    ON CAB.MVVC_NR_ECF_MOV = PRD.MVVP_NR_ECF_MOV
	    AND CAB.MVVC_CD_FILIAL_MOV = PRD.MVVP_CD_FILIAL_MOV 
	    AND CAB.MVVC_DT_MOV = PRD.MVVP_DT_MOV 
	    AND CAB.MVVC_CT_VDA = PRD.MVVP_CT_VDA
	INNER JOIN 
	    modelled.cosmos_v14b_dbo_produto_mestre PM
	    ON PRD.MVVP_NR_PRD = PM.PRME_CD_PRODUTO
	WHERE 
	    CAB.MVVC_DT_MOV >= date_add('day', -50, current_date)
	    AND CAB.MVVC_ST_CAN_CPM <> 'N'
	    AND PM.FARMACIA_POPULAR = 'S'
),
CTE_CANCELADO as (
	SELECT 
        CAST(date_parse(FT.DATA_INVENTARIO, '%d/%m/%Y') AS DATE) AS DATA_INVENTARIO,
        CAST(CAB.MVVC_DT_MOV AS date) AS DATA_CPM,
	    SKU.HORA_AB,
	    SKU.HORA_FC,
	    CONCAT(CAST(CAB.MVVC_CD_FILIAL_MOV AS VARCHAR), '|', CAST(CAB.NUMERO_COO AS VARCHAR)) AS CHV_FLIAL_PRD,
	    SKU.QTD AS SKU,
	    CAST(CAB.MVVC_CD_FILIAL_MOV AS VARCHAR) AS FILIAL, 
	    CAST(CAB.MVVC_NR_ECF_MOV AS VARCHAR) AS ECF,
	    CAST(OPR.STOP_CD_USU_OPR AS VARCHAR) AS CAIXA,
	    CAST(OPCX.USUA_NM_USUARIO AS VARCHAR) AS NOME_OP,
	    CAST(CAB.NUMERO_COO AS VARCHAR) AS NUMERO_COO,
	    CAST(PRD.MVVP_NR_PRD AS VARCHAR) AS COD_PROD,
	    CAST(PM.PRME_NR_DV AS VARCHAR) AS DIG,
	    CAST(PM.PRME_TX_DESCRICAO1 AS VARCHAR) AS DESCRICAO,
	    SUM(CAST(PRD.MVVP_QT_PRD AS INTEGER)) AS QUANT,
	    SUM(CAST(PRD.MVVP_VL_PRD_VEN AS DECIMAL(10, 2))) AS VALOR,
	    CAST(CAB.MVVC_ST_CAN_CPM AS VARCHAR) AS CANC,
	    CAST(CAB.MVVC_CD_USU_T052_CAN AS VARCHAR) AS AUTORIZADOR,
	    CAST(UAT.USUA_NM_USUARIO AS VARCHAR) AS NOME_AUT,
	    CAST(CG.CARG_NM_CARGO AS VARCHAR) AS FUNCAO,
	    CAST(PRD.MVVP_ST_CAN_ITE AS VARCHAR) AS ITEM_CANC,
	    CAST(CAB.DESC_MOTIVO_CANCEL_NFCE AS VARCHAR) AS MOTIVO,
	    CAST(FLT.KAFI_TP_MOV AS VARCHAR) AS TIPO_MOV,
	    CAST(FLT.QTD AS INTEGER) AS QTD_FALTA
	FROM modelled.cosmos_mov_v14b_dbo_mv_vda_cab CAB
	INNER JOIN modelled.cosmos_mov_v14b_dbo_mv_vda_prd PRD
		ON CAB.MVVC_NR_ECF_MOV = PRD.MVVP_NR_ECF_MOV
			AND CAB.MVVC_CD_FILIAL_MOV = PRD.MVVP_CD_FILIAL_MOV 
			AND CAB.MVVC_DT_MOV = PRD.MVVP_DT_MOV 
			AND CAB.MVVC_CT_VDA = PRD.MVVP_CT_VDA
			
	INNER JOIN prevencao_a_fraude.data_inventario AS FT 
		ON FT.KAFI_CD_FILIAL = CAST(CAB.MVVC_CD_FILIAL_MOV AS varchar)
		
	INNER JOIN CTE_CHAVE_COO SKU 
			ON SKU.CHV_FLIAL_PRD = CONCAT(CAST(CAB.MVVC_CD_FILIAL_MOV AS varchar),'|', CAST(CAB.MVVC_NR_ECF_MOV AS varchar),'|', CAST(CAB.NUMERO_COO AS varchar))
	LEFT JOIN CTE_CHAVE_PRD PPL
				ON PPL.CHV_PPL = CONCAT(CAST(CAB.MVVC_CD_FILIAL_MOV AS varchar),'|', CAST(CAB.MVVC_NR_ECF_MOV AS varchar),'|', CAST(CAB.NUMERO_COO AS varchar))
	INNER JOIN modelled.cosmos_v14b_dbo_produto_mestre PM
		ON PRD.MVVP_NR_PRD = PM.PRME_CD_PRODUTO
	INNER JOIN modelled.cosmosmov_v14b_dbo_st_opr OPR
		ON OPR.STOP_CT_ST_OPR = CAB.MVVC_CT_ST_OPR 
			AND OPR.STOP_NR_ECF_MOV = CAB.MVVC_NR_ECF_MOV 
			AND OPR.STOP_CD_FILIAL_MOV = CAB.MVVC_CD_FILIAL_MOV 
			AND OPR.STOP_DT_MOV = CAB.MVVC_DT_MOV
	INNER JOIN modelled.cosmos_v14b_dbo_usuario UAT
		ON CAB.MVVC_CD_USU_T052_CAN = UAT.USUA_CD_USUARIO
	INNER JOIN modelled.cosmos_v14b_dbo_cargo CG
		ON UAT.CARG_CD_CARGO = CG.CARG_CD_CARGO
	INNER JOIN modelled.cosmos_v14b_dbo_usuario OPCX
		ON OPR.STOP_CD_USU_OPR = OPCX.USUA_CD_USUARIO
		
	LEFT JOIN prevencao_a_fraude.qtd_falta FLT 
	ON FLT.KAFI_CD_FILIAL = CAST(PRD.MVVP_CD_FILIAL_MOV AS varchar)
		AND FLT.KAFI_CD_PRODUTO = CAST(PRD.MVVP_NR_PRD AS varchar)
	
	WHERE 1 = 1
	    AND CAB.MVVC_ST_CAN_CPM = 'O'
	    AND CAB.MVVC_DT_MOV >= date_add('day', -50, current_date)
        AND date_parse(FT.DATA_INVENTARIO, '%d/%m/%Y') >= CAB.MVVC_DT_MOV
	    AND PPL.CHV_PPL IS NULL
	    AND CAST(SKU.DIFERENCA_SEGUNDOS AS INTEGER) BETWEEN 30 AND 300
	    AND SKU.TT BETWEEN 11.00 AND 350.00
	    AND SKU.QTD <= 8

	GROUP BY
	    date_parse(FT.DATA_INVENTARIO, '%d/%m/%Y'),
	    CAB.MVVC_DT_MOV,
	    SKU.HORA_AB,
	    SKU.HORA_FC,
	    CONCAT(CAST(CAB.MVVC_CD_FILIAL_MOV AS VARCHAR), '|', CAST(CAB.NUMERO_COO AS VARCHAR)),
	    SKU.QTD,
	    CAB.MVVC_CD_FILIAL_MOV,
	    CAB.MVVC_NR_ECF_MOV,
	    OPR.STOP_CD_USU_OPR,
	    OPCX.USUA_NM_USUARIO,
	    CAB.NUMERO_COO,
	    PRD.MVVP_NR_PRD,
	    PM.PRME_NR_DV,
	    PM.PRME_TX_DESCRICAO1,
	    CAB.MVVC_ST_CAN_CPM,
	    CAB.MVVC_CD_USU_T052_CAN,
	    UAT.USUA_NM_USUARIO,
	    CG.CARG_NM_CARGO,
	    PRD.MVVP_ST_CAN_ITE,
	    CAB.DESC_MOTIVO_CANCEL_NFCE,
	    FLT.KAFI_TP_MOV,
	    FLT.QTD
 )
	SELECT * FROM CTE_CANCELADO
 
	WHERE CHV_FLIAL_PRD NOT IN
	(SELECT CHV_FLIAL_PRD FROM CTE_CANCELADO
	WHERE QTD_FALTA IS NULL
	GROUP BY CHV_FLIAL_PRD)
 
	ORDER BY FILIAL, DATA_CPM, HORA_AB